name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}

      - run: git config user.name 'Release BOT'
      - run: git config user.email 'noreply.release@github.com'

      - name: Install Semversioner
        run: pip install semversioner

      - name: Release
        run: |
          semversioner next-version
          semversioner release
          semversioner changelog > CHANGELOG.md

      - name: Set version
        run: |
          export VERSION=$(semversioner current-version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update files for new version '${{ env.VERSION }}' [skip ci]"
          git push origin master

      - name: Create new tag
        run: |
          git tag -a -m "Tagging for release ${{ env.VERSION }}" "${{ env.VERSION }}"
          git push origin ${{ env.VERSION }}
          git push --tags


